name: Clasharp Build

on:
  push:
    branches:
      - clasharp
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # - name: Install Dotnet
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: | 
      #       7
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Init & Build
        run: |
          cd C:\ ; git clone --depth=1 --recursive https://github.com/moonheart/Clasharp.git -b master
          cd Clasharp\Clasharp
          dotnet publish -c Release
      # - name: Package Directories
      #   run: |
          # 7z a Clasharp.7z C:\Clasharp\release-dir
          # 7z a Clasharp.7z C:\Clasharp\Clasharp\bin\x64\Release\net7.0\publish\
      - uses: actions/upload-artifact@v3
        with:
          name: Clasharp
          path: C:\Clasharp\Clasharp\bin\x64\Release\net7.0\publish\