name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Install Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            8
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Init & Build
        run: |
          cd C:\ ; git clone --depth=1 https://github.com/dotnet/runtime.git
          cd runtime\src\coreclr\tools\dotnet-pgo ; dotnet restore ; dotnet build
          ls